yumroad/models.py
from sqlalchemy.orm import validates
from yumroad.extensions import db

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    description = db.Column(db.String(120), nullable=False)

    @validates('name')
    def validate_name(self, key, name):
        if len(name.strip()) <= 3:
            raise ValueError('needs to have a name')
        return name

yumroad/forms.py
from flask_wtf import FlaskForm

from wtforms.fields import StringField, SubmitField
from wtforms.validators import Length


class ProductForm(FlaskForm):
    name = StringField('Name', [Length(min=4, max=60)])
    description = StringField('Description')
    submit = SubmitField('Create')

yumroad/__init__.py
from flask import Flask, render_template
from yumroad.blueprints.products import products
from yumroad.config import configurations
from yumroad.extensions import (db)


def create_app(environment_name='dev'):
    app = Flask(__name__)
    app.config.from_object(configurations[environment_name])
    db.init_app(app)
    app.register_blueprint(products, url_prefix="/product")
    return app

yumroad/blueprints/products.py
from flask import Blueprint, render_template, request, redirect, url_for

from yumroad.forms import ProductForm
from yumroad.models import Product
from yumroad.extensions import db

products = Blueprint('products', __name__)


@products.route('/')
def index():
    all_products = Product.query.all()
    return render_template('products/index.html', products=all_products)


@products.route('/<int:product_id>')
def details(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('products/details.html', product=product)


@products.route('/create', methods=['GET', 'POST'])
def create():
    form = ProductForm()
    if form.validate_on_submit():
        product = Product(name=form.name.data, description=form.description.data)
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('.details', product_id=product.id))
    return render_template('products/new.html', form=form)


@products.route('/<product_id>/edit', methods=['GET', 'POST'])
def edit(product_id):
    product = Product.query.get_or_404(product_id)
    form = ProductForm(product)
    if form.validate_on_submit():
        product.name = form.name.data
        product.description = form.description.data
        db.session.add(product)
        db.session.commit()
    return render_template('products/edit.html', form=form, product=product)


@products.errorhandler(404)
def not_found(exception):
    return render_template('products/404.html'), 404

yumroad/templates/_formhelpers.html
{% macro render_field(field) %}
    <div class="form-group {% if field.errors %} has-error{% endif -%}
                            {%- if field.flags.required %} required{% endif -%}">
        <label for="{{ field.name }}">{{ field.label }}</label>
        {{ field(class_=' '.join(['form-control', 'is-invalid' if field.errors else '']), **kwargs)|safe }}
        <ul class="invalid-feedback errors">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

yumroad/templates/base_layout.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}{% endblock %} Yumroad
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">Yumroad</a>
</nav>
<div class="container mt-3">
    {% block content %}{% endblock %}
</div>
</body>
</html>

yumroad/templates/products/details.html
{% extends "base_layout.html" %}
{% block title %} {{ product.name }} {% endblock %}
{% block content %}
    <div class="container">
        <h1> {{ product.name }} </h1>
        <hr/>
        <span> {{ product.description }} </span>
        <hr/>
        <button> Purchase coming soon!</button>
    </div>
{% endblock %}

yumroad/templates/products/edit.html
{% extends "base_layout.html" %}
{% from "_formhelpers.html" import render_field %}

{% block title %} Edit {{ product.name }} {% endblock %}
{% block content %}
    <div class="container">
        <form method="POST" action="{{ url_for('products.edit', product_id=product.id) }}">
            {{ render_field(form.name) }}
            {{ render_field(form.description) }}
            <button type="submit" class="btn btn-primary">Edit</button>
            Handling Forms (with WTForms) 107
        </form>
    </div>
{% endblock %}

yumroad/templates/products/index.html
{% extends "base_layout.html" %}
{% block title %} All Products {% endblock %}
{% block content %}
    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <th scope="row">
                        <a href="{{ url_for('products.details', product_id=product.id) }}">
                            {{ product.name }}
                        </a>
                    </th>
                    <th scope="row">{{ product.description }}</th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

yumroad/templates/products/new.html
{% extends "base_layout.html" %}
{% from "_formhelpers.html" import render_field %}

{% block title %} New Product {% endblock %}

{% block content %}
  <div class="container">

    <form method="POST" action="{{ url_for('products.create') }}">
      {{ form.csrf_token }}

      {{ render_field(form.name) }}
      {{ render_field(form.description) }}
      <button type="submit" class="btn btn-primary">Create</button>
    </form>

  </div>
{% endblock %}